#MatPlotLib
#used to show in form of graphs
import matplotlib.pyplot as plt
import numpy as np
x= np.array((0, 5))
y= np.array((1, 7))
plt.plot(x, y)
plt.show()
x= np.array((2,3, 5, 9, 10))
y= np.array((23, 2, 29, 93, 10))
plt.plot(x, y, marker= '+', linestyle= 'dotted')
plt.title('Line Graph')
plt.xlabel('X-Axis')
plt.ylabel('Y-Axis')
plt.show()
plt.bar(x, y, 1)
plt.title('Bar Chart')
plt.xlabel('X-Axis')
plt.ylabel('Y-Axis')
plt.show()
plt.scatter(x, y, marker='*')
plt.title('Scatter Plot')
plt.show()
plt.hist(x)
plt.title('Histogram')
plt.show()
plt.pie(x, labels= x)
plt.title('Pie Chart')
plt.show()
